server:
  port: 8222
api:
  prefix: ${API_VERSION}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: identity-service
          uri: ${IDENTITY_SERVICE}
          predicates:
            - Path=${api.prefix}/accounts/**, ${api.prefix}/auth/**
          filters:
            - StripPrefix=2
        - id: customer-service
          uri: ${CUSTOMER_SERVICE}
          predicates:
            - Path=${api.prefix}/customers/**
          filters:
            - StripPrefix=2
        - id: product-service
          uri: ${PRODUCT_SERVICE}
          predicates:
            - Path=${api.prefix}/brands/**, ${api.prefix}/categories/**, ${api.prefix}/products/**, ${api.prefix}/uploads/**
          filters:
            - StripPrefix=2
services:
  identity: ${IDENTITY_SERVICE}