spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: ${IDENTITY_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: emailRequest:com.dattran.identity_service.app.requests.EmailRequest
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
server:
  port: 8080
jwt:
  secret-key: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_S}
  refresh-key: ${JWT_REFRESH_SECRET}
  expiration-rf-key: ${JWT_REFRESH_EXPIRATION_S}
otp:
  expiration: ${OTP_EXPIRATION_MINUTES}
services:
  customer: ${CUSTOMER_SERVICE}
  notification: ${NOTIFICATION_SERVICE}
